spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.189:3306/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-pms
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 7020
